# Generated by Django 3.1.5 on 2022-05-04 17:57

from django.db import migrations, models
import support.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=support.utils.random_key, max_length=13, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=30, null=True)),
                ('text', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_readed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MassEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=support.utils.random_key, max_length=13, unique=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('admin_name', models.CharField(blank=True, max_length=30, null=True)),
                ('subject', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
    ]
